@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jan 08 18:19:12 +0800 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim minisys_sim_behav -key {Behavioral:sim_1:Functional:minisys_sim} -tclbatch minisys_sim.tcl -view E:/Sysdesign/minisys/minisys_sim_behav.wcfg -view E:/Sysdesign/minisys/idecode_sim_behav.wcfg -log simulate.log"
call xsim  minisys_sim_behav -key {Behavioral:sim_1:Functional:minisys_sim} -tclbatch minisys_sim.tcl -view E:/Sysdesign/minisys/minisys_sim_behav.wcfg -view E:/Sysdesign/minisys/idecode_sim_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
